### ISSUE TITLE
extract plaf from vcf

### ISSUE THREAD

**Issue by shajoezhu** [DEploid-dev/DEploid#142]
Extract AF from VCF

eg. 

AC=22;**AF=0.012**;AN=64;

**Comment by dcastaneda5** [comment]
Hi! I am new to DEploid and I am currently trying to figure out different haplotypes across a set of patients from Ethiopia. I was wondering if there's a way of extracting the plaf file from a vcf file, given that I do not have with me the population level of the strains. Is that possible?

thanks!

**Comment by shajoezhu** [comment]
Hi @dcastaneda5 , I have a separate script to extract all # of ALT and all # of REF at the site j, and compute PLAF as sum(ALT)/sum(ALT+REF) over all samples. Been meaning to include this operation into the program, just haven't got around to do it. In some VCF files, PLAF is already given, I assume this is not the case for you?

**Comment by dcastaneda5** [comment]
I see. No, in my vcf file I am not getting the PLAF that is needed. You say it is found at the site j? Can I access to it so I can use it to run DEploid?

Many thanks!
